apps:api:
  - changed-files:
      - any-glob-to-any-file: apps/api/**

apps:web:
  - changed-files:
      - any-glob-to-any-file: apps/web/**

packages:
  - changed-files:
      - any-glob-to-any-file: packages/**

test:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.ts"
          - "**/*.test.tsx"
