name: DeleteMergedBranch

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete Branches
        run: |
          git branch -r --merged=main | grep -vE '^\s*origin/(main$|develop$|HEAD$)' | sed 's/origin\///' | xargs git push --delete origin